parameters:
- name: Environment
  type: string
- name: ShareEnvironment
  type: string
- name: EnableShareModel
  type: boolean
- name: EnableShareEnvironment
  type: boolean
- name: EnableCreateOnlineEndpoint
  type: boolean
- name: EnableCreateOnlineDeployment
  type: boolean
- name: EnableSetEndpointTraffic
  type: boolean

jobs:
- deployment: ShareModel
  displayName: Share Model to Registry - ${{ parameters.Environment }}
  condition: eq('${{ parameters.EnableShareModel }}', 'true')
  environment: ${{ parameters.Environment }}
  variables:
    - template: ./configuration/variables-${{ parameters.ShareEnvironment }}.yaml
  strategy:
    runOnce:
      deploy:
        steps:
          - template: ./model/share-model.yaml
            parameters:
              Environment: ${{ parameters.Environment }}

- deployment: ShareEnvironment
  displayName: Share Environment to Registry - ${{ parameters.Environment }}
  condition: eq('${{ parameters.EnableShareEnvironment }}', 'true')
  dependsOn:
    - ShareModel
  environment: ${{ parameters.Environment }}
  variables:
    - template: ./configuration/variables-${{ parameters.ShareEnvironment }}.yaml
  strategy:
    runOnce:
      deploy:
        steps:
          - template: ./environment/share-environment.yaml
            parameters:
              Environment: ${{ parameters.Environment }}

- deployment: CreateOnlineEndpoint
  displayName: Create Online Endpoint - ${{ parameters.Environment }}
  condition: eq('${{ parameters.EnableCreateOnlineEndpoint }}', 'true')
  dependsOn:
    - ShareEnvironment
  environment: ${{ parameters.Environment }}
  variables:
    - template: ./configuration/variables-${{ parameters.Environment }}.yaml
  strategy:
    runOnce:
      deploy:
        steps:
          - template: ./endpoint/create-online-endpoint.yaml
            parameters:
              Environment: ${{ parameters.Environment }}

- deployment: CreateOnlineDeployment
  displayName: Create Deployment on Endpoint - ${{ parameters.Environment }}
  condition: eq('${{ parameters.EnableCreateOnlineDeployment }}', 'true')
  dependsOn:
    - CreateOnlineEndpoint
  environment: ${{ parameters.Environment }}
  variables:
    - template: ./configuration/variables-${{ parameters.Environment }}.yaml
  strategy:
    runOnce:
      deploy:
        steps:
          - template: ./deployment/create-online-deployment.yaml
            parameters:
              Environment: ${{ parameters.Environment }}

- deployment: SetEndpointTraffic
  displayName: Set Traffic on Endpoint - ${{ parameters.Environment }}
  condition: eq('${{ parameters.EnableSetEndpointTraffic }}', 'true')
  dependsOn:
  - CreateOnlineDeployment
  environment: ${{ parameters.Environment }}
  variables:
    - template: ./configuration/variables-${{ parameters.Environment }}.yaml
  strategy:
    runOnce:
      deploy:
        steps:
          - template: ./endpoint/set-endpoint-traffic.yaml
            parameters:
              Environment: ${{ parameters.Environment }}