parameters:
- name: Environment
  type: string

steps:
- checkout: self

- task: AzureCLI@2
  displayName: "Install Azure CLI"
  inputs:
    azureSubscription: arm-mlops-demo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az version
      az extension add --name ml --yes --upgrade
      az configure --defaults group=$(ResourceGroup) workspace=$(WorkspaceName)

- task: AzureCLI@2
  displayName: "Create Endpoint in Azure ML"
  inputs:
    azureSubscription: arm-mlops-demo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az ml online-endpoint create \
      --name $(EndpointName) \
      --auth-mode key

- task: AzureCLI@2
  displayName: "Get Endpoint Information"
  inputs:
    azureSubscription: arm-mlops-demo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      SCORING_URI=$(az ml online-endpoint show --name $(EndpointName) --query scoring_uri -o tsv)
      SWAGGER_URI=$(az ml online-endpoint show --name $(EndpointName) --query openapi_uri -o tsv)
      PRIMARY_KEY=$(az ml online-endpoint get-credentials --name $(EndpointName) --query primaryKey -o tsv)
      SECONDARY_KEY=$(az ml online-endpoint get-credentials --name $(EndpointName) --query secondaryKey -o tsv)

      echo "##vso[task.setvariable variable=EndpointScoringUri]$SCORING_URI"
      echo "##vso[task.setvariable variable=EndpointSwaggerUri]$SWAGGER_URI"
      echo "##vso[task.setvariable variable=EndpointPrimaryKey]$PRIMARY_KEY"
      echo "##vso[task.setvariable variable=EndpointSecondaryKey]$SECONDARY_KEY"

- task: AzureCLI@2
  displayName: "Store Scoring URI in Key Vault"
  inputs:
    azureSubscription: arm-mlops-demo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az keyvault secret set --vault-name $(KeyVaultName) --name "$(EndpointName)-scoring-uri" --value "$(EndpointScoringUri)"

- task: AzureCLI@2
  displayName: "Store Endpoint Swagger URI in Key Vault"
  inputs:
    azureSubscription: arm-mlops-demo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az keyvault secret set --vault-name $(KeyVaultName) --name "$(EndpointName)-swagger-uri" --value "$(EndpointSwaggerUri)"

- task: AzureCLI@2
  displayName: "Store Endpoint Primary Key in Key Vault"
  inputs:
    azureSubscription: arm-mlops-demo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az keyvault secret set --vault-name $(KeyVaultName) --name "$(EndpointName)-primary-key" --value "$(EndpointPrimaryKey)"

- task: AzureCLI@2
  displayName: "Store Endpoint Secondary Key in Key Vault"
  inputs:
    azureSubscription: arm-mlops-demo
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az keyvault secret set --vault-name $(KeyVaultName) --name "$(EndpointName)-secondary-key" --value "$(EndpointSecondaryKey)"