parameters:
- name: Environment
  type: string

steps:
- checkout: self

- script: |
    echo "PipelineServiceConnection: $(PipelineServiceConnection)"
  displayName: "Debug Service Connection Variable"

- task: AzureCLI@2
  displayName: "Install Azure CLI"
  inputs:
    azureSubscription: $(PipelineServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az version
      az extension add --name ml --yes --upgrade
      az configure --defaults group=$(ResourceGroup) workspace=$(WorkspaceName)

- task: AzureCLI@2
  displayName: "Register Model in Azure ML"
  inputs:
    azureSubscription: $(PipelineServiceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az ml model create \
      --name $(ModelName) \
      --version $(ModelVersion) \
      --type $(ModelType) \
      --path azureml://jobs/$(JobName)/outputs/model/$(ModelArtifactName)
